version: '3'
 
services:
    green_web:
        container_name: ${COMPOSE_PROJECT_NAME}_green
        build: ./nginx/green
        expose:
            - ${NGINX_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${green_IP}
    blue_web:
        container_name: ${COMPOSE_PROJECT_NAME}_blue
        build: ./nginx/blue
        expose:
            - ${NGINX_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${blue_IP}
    haproxy:
        build: ./haproxy
        links:
            - green_web
            - blue_web
        ports:
            - ${NGINX_DEFAULT_PORT}:${NGINX_EXPOSED_PORT}
        expose:
            - ${NGINX_EXPOSED_PORT}
        networks:
            public_net:
                ipv4_address: ${HA_PROXY_IP}
        environment:
            - green_web=${green_IP}
            - blue_web=${blue_IP}
            - NGINX_EXPOSED_PORT=${NGINX_EXPOSED_PORT}
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}