---
- name: Install PostgreSQL
  apt:
    name:
    - python3-pip
    - postgresql
    - postgresql-contrib
    - build-essential
    - libpq-dev
    - python-dev
    - python-psycopg2
  tags: packages

- name: install pips
  pip: name=psycopg2
- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become_user: postgres
  postgresql_db: name=example_db
    encoding='UTF-8'
    lc_collate='en_US.UTF-8'
    lc_ctype='en_US.UTF-8'
    template='template0'
    state=present

- name: Ensure user has access to the database
  become_user: postgres
  postgresql_user: db=example_db
    name=example_user
    password=supersecure
    priv=ALL
    state=present

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  postgresql_user: name=example_user
    role_attr_flags=NOSUPERUSER,NOCREATEDB
    state=present
